# Generated by Django 2.2.6 on 2019-10-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parciales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialdeestudio',
            name='archivo',
        ),
        migrations.AlterField(
            model_name='materialdeestudio',
            name='materia',
            field=models.CharField(max_length=30),
        ),
    ]
